2025-09-18 18:33:46,975 django.request WARNING  Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-09-18 18:34:55,278 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/tables.py changed, reloading.
2025-09-18 18:34:56,114 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 18:34:58,645 django.request ERROR    Internal Server Error: /quotes/
Traceback (most recent call last):
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 890, in _resolve_lookup
    raise TypeError
TypeError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 1075, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 722, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 854, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 901, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/billing/tables.py", line 58, in url
    print('\n \n\ n>>>>', self.model)
                          ^^^^^^^^^^
AttributeError: 'BillHtmxTable' object has no attribute 'model'
2025-09-18 18:34:58,813 django.request WARNING  Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-09-18 18:35:28,226 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/tables.py changed, reloading.
2025-09-18 18:35:29,069 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 18:35:37,310 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/tables.py changed, reloading.
2025-09-18 18:35:38,171 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 18:35:47,452 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/views.py changed, reloading.
2025-09-18 18:35:48,258 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 18:35:55,485 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/views.py changed, reloading.
2025-09-18 18:35:56,309 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 18:36:05,451 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/views.py changed, reloading.
2025-09-18 18:36:06,212 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 18:37:14,948 django.request WARNING  Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-09-18 18:37:27,103 django.request ERROR    Internal Server Error: /quotes/
Traceback (most recent call last):
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_filters/views.py", line 85, in get
    context = self.get_context_data(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/billing/views.py", line 47, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/core/mixins.py", line 38, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/views.py", line 161, in get_context_data
    table = self.get_table(**self.get_table_kwargs())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/views.py", line 123, in get_table
    return RequestConfig(self.request, paginate=self.get_table_pagination(table)).configure(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/config.py", line 44, in configure
    table.order_by = order_by
    ^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/tables.py", line 542, in order_by
    self.data.order_by(self._order_by)
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/data.py", line 224, in order_by
    self.data = self.data.order_by(*order_by_accessors)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1722, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2291, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1805, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'get_total_ttc' into field. Choices are: bill_discount, bill_number, bill_total, bill_type, bill_year, created_at, created_by, created_by_id, creation_date, due_date, expiration_date, id, lead, lead_id, lines, notes, payments, state, updated_at, updated_by, updated_by_id
2025-09-18 18:37:27,601 django.request ERROR    Internal Server Error: /quotes/
Traceback (most recent call last):
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_filters/views.py", line 85, in get
    context = self.get_context_data(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/billing/views.py", line 47, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/core/mixins.py", line 38, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/views.py", line 161, in get_context_data
    table = self.get_table(**self.get_table_kwargs())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/views.py", line 123, in get_table
    return RequestConfig(self.request, paginate=self.get_table_pagination(table)).configure(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/config.py", line 44, in configure
    table.order_by = order_by
    ^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/tables.py", line 542, in order_by
    self.data.order_by(self._order_by)
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/data.py", line 224, in order_by
    self.data = self.data.order_by(*order_by_accessors)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1722, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2291, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1805, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'get_total_ttc' into field. Choices are: bill_discount, bill_number, bill_total, bill_type, bill_year, created_at, created_by, created_by_id, creation_date, due_date, expiration_date, id, lead, lead_id, lines, notes, payments, state, updated_at, updated_by, updated_by_id
2025-09-18 18:37:28,414 django.request ERROR    Internal Server Error: /quotes/
Traceback (most recent call last):
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_filters/views.py", line 85, in get
    context = self.get_context_data(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/billing/views.py", line 47, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/core/mixins.py", line 38, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/views.py", line 161, in get_context_data
    table = self.get_table(**self.get_table_kwargs())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/views.py", line 123, in get_table
    return RequestConfig(self.request, paginate=self.get_table_pagination(table)).configure(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/config.py", line 44, in configure
    table.order_by = order_by
    ^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/tables.py", line 542, in order_by
    self.data.order_by(self._order_by)
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/data.py", line 224, in order_by
    self.data = self.data.order_by(*order_by_accessors)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1722, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2291, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1805, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'rest_amount' into field. Choices are: bill_discount, bill_number, bill_total, bill_type, bill_year, created_at, created_by, created_by_id, creation_date, due_date, expiration_date, id, lead, lead_id, lines, notes, payments, state, updated_at, updated_by, updated_by_id
2025-09-18 18:37:28,766 django.request ERROR    Internal Server Error: /quotes/
Traceback (most recent call last):
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_filters/views.py", line 85, in get
    context = self.get_context_data(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/billing/views.py", line 47, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/core/mixins.py", line 38, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/views.py", line 161, in get_context_data
    table = self.get_table(**self.get_table_kwargs())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/views.py", line 123, in get_table
    return RequestConfig(self.request, paginate=self.get_table_pagination(table)).configure(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/config.py", line 44, in configure
    table.order_by = order_by
    ^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/tables.py", line 542, in order_by
    self.data.order_by(self._order_by)
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/data.py", line 224, in order_by
    self.data = self.data.order_by(*order_by_accessors)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1722, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2291, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1805, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'rest_amount' into field. Choices are: bill_discount, bill_number, bill_total, bill_type, bill_year, created_at, created_by, created_by_id, creation_date, due_date, expiration_date, id, lead, lead_id, lines, notes, payments, state, updated_at, updated_by, updated_by_id
2025-09-18 18:37:29,259 django.request ERROR    Internal Server Error: /quotes/
Traceback (most recent call last):
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_filters/views.py", line 85, in get
    context = self.get_context_data(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/billing/views.py", line 47, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/core/mixins.py", line 38, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/views.py", line 161, in get_context_data
    table = self.get_table(**self.get_table_kwargs())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/views.py", line 123, in get_table
    return RequestConfig(self.request, paginate=self.get_table_pagination(table)).configure(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/config.py", line 44, in configure
    table.order_by = order_by
    ^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/tables.py", line 542, in order_by
    self.data.order_by(self._order_by)
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/data.py", line 224, in order_by
    self.data = self.data.order_by(*order_by_accessors)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1722, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2291, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1805, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'get_due_date_with_number_of_days' into field. Choices are: bill_discount, bill_number, bill_total, bill_type, bill_year, created_at, created_by, created_by_id, creation_date, due_date, expiration_date, id, lead, lead_id, lines, notes, payments, state, updated_at, updated_by, updated_by_id
2025-09-18 18:37:29,680 django.request ERROR    Internal Server Error: /quotes/
Traceback (most recent call last):
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_filters/views.py", line 85, in get
    context = self.get_context_data(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/billing/views.py", line 47, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/core/mixins.py", line 38, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/views.py", line 161, in get_context_data
    table = self.get_table(**self.get_table_kwargs())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/views.py", line 123, in get_table
    return RequestConfig(self.request, paginate=self.get_table_pagination(table)).configure(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/config.py", line 44, in configure
    table.order_by = order_by
    ^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/tables.py", line 542, in order_by
    self.data.order_by(self._order_by)
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/data.py", line 224, in order_by
    self.data = self.data.order_by(*order_by_accessors)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1722, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2291, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1805, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'get_due_date_with_number_of_days' into field. Choices are: bill_discount, bill_number, bill_total, bill_type, bill_year, created_at, created_by, created_by_id, creation_date, due_date, expiration_date, id, lead, lead_id, lines, notes, payments, state, updated_at, updated_by, updated_by_id
2025-09-18 18:37:35,937 django.request WARNING  Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-09-18 18:38:24,256 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/tables.py changed, reloading.
2025-09-18 18:38:25,124 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 18:38:31,343 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/tables.py changed, reloading.
2025-09-18 18:38:32,164 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 18:38:47,703 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/tables.py changed, reloading.
2025-09-18 18:38:48,579 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 18:38:54,828 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/tables.py changed, reloading.
2025-09-18 18:38:55,677 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 18:39:08,286 django.request ERROR    Internal Server Error: /quotes/company/3/
Traceback (most recent call last):
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_filters/views.py", line 85, in get
    context = self.get_context_data(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/billing/views.py", line 47, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/core/mixins.py", line 38, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/views.py", line 161, in get_context_data
    table = self.get_table(**self.get_table_kwargs())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/views.py", line 122, in get_table
    table = table_class(data=self.get_table_data(), **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Table.__init__() got an unexpected keyword argument 'company_pk'
2025-09-18 18:40:04,250 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/views.py changed, reloading.
2025-09-18 18:40:05,156 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 18:40:11,448 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/views.py changed, reloading.
2025-09-18 18:40:12,316 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 18:40:30,900 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/views.py changed, reloading.
2025-09-18 18:40:31,740 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 18:44:07,012 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/tables.py changed, reloading.
2025-09-18 18:44:07,902 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 18:44:17,920 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/tables.py changed, reloading.
2025-09-18 18:44:18,829 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 18:44:20,931 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/tables.py changed, reloading.
2025-09-18 18:44:21,761 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 18:44:27,113 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/tables.py changed, reloading.
2025-09-18 18:44:27,973 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 18:44:30,298 django.request ERROR    Internal Server Error: /invoices/company/3/
Traceback (most recent call last):
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_filters/views.py", line 85, in get
    context = self.get_context_data(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/billing/views.py", line 47, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/core/mixins.py", line 38, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/views.py", line 161, in get_context_data
    table = self.get_table(**self.get_table_kwargs())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/views.py", line 123, in get_table
    return RequestConfig(self.request, paginate=self.get_table_pagination(table)).configure(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/config.py", line 44, in configure
    table.order_by = order_by
    ^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/tables.py", line 542, in order_by
    self.data.order_by(self._order_by)
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/data.py", line 224, in order_by
    self.data = self.data.order_by(*order_by_accessors)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1722, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2291, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1805, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'get_total_ttc' into field. Choices are: bill_discount, bill_number, bill_total, bill_type, bill_year, created_at, created_by, created_by_id, creation_date, due_date, expiration_date, id, lead, lead_id, lines, notes, payments, state, updated_at, updated_by, updated_by_id
2025-09-18 18:44:30,578 django.request ERROR    Internal Server Error: /invoices/company/3/
Traceback (most recent call last):
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_filters/views.py", line 85, in get
    context = self.get_context_data(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/billing/views.py", line 47, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/core/mixins.py", line 38, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/views.py", line 161, in get_context_data
    table = self.get_table(**self.get_table_kwargs())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/views.py", line 123, in get_table
    return RequestConfig(self.request, paginate=self.get_table_pagination(table)).configure(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/config.py", line 44, in configure
    table.order_by = order_by
    ^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/tables.py", line 542, in order_by
    self.data.order_by(self._order_by)
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/data.py", line 224, in order_by
    self.data = self.data.order_by(*order_by_accessors)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1722, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2291, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1805, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'get_total_ttc' into field. Choices are: bill_discount, bill_number, bill_total, bill_type, bill_year, created_at, created_by, created_by_id, creation_date, due_date, expiration_date, id, lead, lead_id, lines, notes, payments, state, updated_at, updated_by, updated_by_id
2025-09-18 18:44:38,958 django.request ERROR    Internal Server Error: /invoices/company/3/
Traceback (most recent call last):
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_filters/views.py", line 85, in get
    context = self.get_context_data(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/billing/views.py", line 47, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/core/mixins.py", line 38, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/views.py", line 161, in get_context_data
    table = self.get_table(**self.get_table_kwargs())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/views.py", line 123, in get_table
    return RequestConfig(self.request, paginate=self.get_table_pagination(table)).configure(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/config.py", line 44, in configure
    table.order_by = order_by
    ^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/tables.py", line 542, in order_by
    self.data.order_by(self._order_by)
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_tables2/data.py", line 224, in order_by
    self.data = self.data.order_by(*order_by_accessors)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1722, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2291, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1805, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'rest_amount' into field. Choices are: bill_discount, bill_number, bill_total, bill_type, bill_year, created_at, created_by, created_by_id, creation_date, due_date, expiration_date, id, lead, lead_id, lines, notes, payments, state, updated_at, updated_by, updated_by_id
2025-09-18 18:44:50,928 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/tables.py changed, reloading.
2025-09-18 18:44:51,761 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 18:47:33,623 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/models.py changed, reloading.
2025-09-18 18:47:34,457 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 18:48:05,286 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/views.py changed, reloading.
2025-09-18 18:48:06,091 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 18:48:14,296 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/views.py changed, reloading.
2025-09-18 18:48:15,211 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 18:48:20,494 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/views.py changed, reloading.
2025-09-18 18:48:21,364 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 18:48:28,635 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/views.py changed, reloading.
2025-09-18 18:48:29,489 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 18:49:13,032 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/views.py changed, reloading.
2025-09-18 18:49:13,889 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 18:49:33,444 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/views.py changed, reloading.
2025-09-18 18:49:34,269 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 18:49:44,956 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/views.py changed, reloading.
2025-09-18 18:49:45,782 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 18:50:02,226 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/views.py changed, reloading.
2025-09-18 18:50:03,036 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 18:50:05,692 django.request ERROR    Internal Server Error: /bills/5/
Traceback (most recent call last):
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/detail.py", line 113, in get
    context = self.get_context_data(object=self.object)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/billing/views.py", line 138, in get_context_data
    context["title"] = self.object.get_bill_type_display + " " + str(self.object.bill_number)
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for +: 'functools.partial' and 'str'
2025-09-18 18:50:11,444 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/views.py changed, reloading.
2025-09-18 18:50:12,252 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 18:50:18,440 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/views.py changed, reloading.
2025-09-18 18:50:19,268 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 18:50:24,426 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/views.py changed, reloading.
2025-09-18 18:50:25,251 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 18:51:07,503 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 18:51:08,392 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 18:51:16,619 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/views.py changed, reloading.
2025-09-18 18:51:17,441 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 18:54:33,049 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/crm/forms.py changed, reloading.
2025-09-18 18:54:33,880 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 18:57:58,179 django.request WARNING  Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-09-18 18:58:13,406 django.request WARNING  Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-09-18 18:58:15,257 django.request WARNING  Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-09-18 18:59:06,319 django.request WARNING  Not Found: /favicon.ico
2025-09-18 19:03:24,946 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 19:03:25,792 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:04:05,952 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 19:04:06,773 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:04:14,407 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 19:04:15,213 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:04:33,854 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 19:04:34,671 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:04:38,777 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 19:04:39,557 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:04:41,647 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 19:04:42,441 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:04:55,876 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 19:04:56,681 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:04:58,150 django.request ERROR    Internal Server Error: /bills/7/
Traceback (most recent call last):
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/detail.py", line 113, in get
    context = self.get_context_data(object=self.object)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/billing/views.py", line 134, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/core/mixins.py", line 41, in get_context_data
    list_url = model.get_list_url() if hasattr(model, "get_list_url") else None
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/core/models.py", line 24, in get_list_url
    return reverse(f"{cls._meta.app_label}:list_{cls._meta.model_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'list_bill' not found. 'list_bill' is not a valid view function or pattern name.
2025-09-18 19:05:41,923 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/models.py changed, reloading.
2025-09-18 19:05:42,740 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:05:51,972 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/models.py changed, reloading.
2025-09-18 19:05:52,761 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:05:54,831 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/models.py changed, reloading.
2025-09-18 19:05:55,615 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:06:00,047 django.request ERROR    Internal Server Error: /bills/7/
Traceback (most recent call last):
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/detail.py", line 113, in get
    context = self.get_context_data(object=self.object)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/billing/views.py", line 134, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/core/mixins.py", line 41, in get_context_data
    list_url = model.get_list_url() if hasattr(model, "get_list_url") else None
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/core/models.py", line 24, in get_list_url
    return reverse(f"{cls._meta.app_label}:list_{cls._meta.model_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'list_bill' not found. 'list_bill' is not a valid view function or pattern name.
2025-09-18 19:06:05,497 django.request ERROR    Internal Server Error: /bills/5/
Traceback (most recent call last):
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/detail.py", line 113, in get
    context = self.get_context_data(object=self.object)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/billing/views.py", line 134, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/core/mixins.py", line 41, in get_context_data
    list_url = model.get_list_url() if hasattr(model, "get_list_url") else None
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/core/models.py", line 24, in get_list_url
    return reverse(f"{cls._meta.app_label}:list_{cls._meta.model_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'list_bill' not found. 'list_bill' is not a valid view function or pattern name.
2025-09-18 19:06:28,845 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/models.py changed, reloading.
2025-09-18 19:06:29,661 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:06:39,073 django.request ERROR    Internal Server Error: /bills/5/
Traceback (most recent call last):
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/detail.py", line 113, in get
    context = self.get_context_data(object=self.object)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/billing/views.py", line 134, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/core/mixins.py", line 41, in get_context_data
    list_url = model.get_list_url() if hasattr(model, "get_list_url") else None
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/core/models.py", line 24, in get_list_url
    return reverse(f"{cls._meta.app_label}:list_{cls._meta.model_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'list_bill' not found. 'list_bill' is not a valid view function or pattern name.
2025-09-18 19:06:39,364 django.request WARNING  Not Found: /favicon.ico
2025-09-18 19:06:59,606 django.request ERROR    Internal Server Error: /bills/5/
Traceback (most recent call last):
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/detail.py", line 113, in get
    context = self.get_context_data(object=self.object)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/billing/views.py", line 134, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/core/mixins.py", line 41, in get_context_data
    list_url = model.get_list_url() if hasattr(model, "get_list_url") else None
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/core/models.py", line 24, in get_list_url
    return reverse(f"{cls._meta.app_label}:list_{cls._meta.model_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'list_bill' not found. 'list_bill' is not a valid view function or pattern name.
2025-09-18 19:07:15,869 django.request ERROR    Internal Server Error: /bills/5/
Traceback (most recent call last):
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/detail.py", line 113, in get
    context = self.get_context_data(object=self.object)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/billing/views.py", line 134, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/core/mixins.py", line 41, in get_context_data
    print('model:>>>>>>>>>>>>>>>>>>>>', model)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/core/models.py", line 24, in get_list_url
    return reverse(f"{cls._meta.app_label}:list_{cls._meta.model_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'list_bill' not found. 'list_bill' is not a valid view function or pattern name.
2025-09-18 19:07:16,117 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 19:07:16,909 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:07:23,087 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 19:07:23,894 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:07:29,015 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 19:07:29,814 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:07:34,668 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:12:03,936 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 19:12:04,741 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:12:07,830 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 19:12:08,629 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:12:47,701 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/views.py changed, reloading.
2025-09-18 19:12:48,517 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:13:21,563 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 19:13:22,421 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:13:26,563 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/views.py changed, reloading.
2025-09-18 19:13:27,361 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:13:40,166 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/views.py changed, reloading.
2025-09-18 19:13:41,032 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:14:11,946 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/models.py changed, reloading.
2025-09-18 19:14:12,776 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:14:19,994 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/models.py changed, reloading.
2025-09-18 19:14:20,865 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:17:41,924 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/urls.py changed, reloading.
2025-09-18 19:17:42,742 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:17:49,938 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/urls.py changed, reloading.
2025-09-18 19:17:50,752 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:17:52,840 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/urls.py changed, reloading.
2025-09-18 19:17:53,685 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:18:48,249 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/views.py changed, reloading.
2025-09-18 19:18:49,050 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:19:38,662 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 19:19:39,493 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:19:43,665 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 19:19:44,514 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:19:49,686 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 19:19:50,522 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:20:07,501 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/urls.py changed, reloading.
2025-09-18 19:20:08,310 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:20:56,824 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 19:20:57,657 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:21:30,662 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 19:21:31,492 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:21:33,626 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 19:21:34,421 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:22:01,159 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/views.py changed, reloading.
2025-09-18 19:22:01,995 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:22:20,660 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 19:22:21,478 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:22:25,624 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 19:22:26,437 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:23:02,487 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/forms.py changed, reloading.
2025-09-18 19:23:03,310 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:23:45,693 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/crm/forms.py changed, reloading.
2025-09-18 19:23:46,542 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:24:01,006 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/forms.py changed, reloading.
2025-09-18 19:24:01,815 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:24:04,932 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/crm/forms.py changed, reloading.
2025-09-18 19:24:05,756 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:24:09,897 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/forms.py changed, reloading.
2025-09-18 19:24:10,723 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:24:12,805 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/forms.py changed, reloading.
2025-09-18 19:24:13,647 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:24:21,915 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/forms.py changed, reloading.
2025-09-18 19:24:22,720 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:24:29,934 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/forms.py changed, reloading.
2025-09-18 19:24:30,764 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:25:20,334 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 19:25:21,169 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:26:29,124 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 19:26:29,986 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:28:09,755 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/urls.py changed, reloading.
2025-09-18 19:28:10,596 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:28:19,870 django.request ERROR    Internal Server Error: /invoices/lead/create/5/
Traceback (most recent call last):
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/edit.py", line 142, in get
    return self.render_to_response(self.get_context_data())
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/core/mixins.py", line 118, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/edit.py", line 72, in get_context_data
    kwargs["form"] = self.get_form()
                     ^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/edit.py", line 37, in get_form
    return form_class(**self.get_form_kwargs())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/billing/forms.py", line 148, in __init__
    self.fields.pop("company")
KeyError: 'company'
2025-09-18 19:28:31,828 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/forms.py changed, reloading.
2025-09-18 19:28:32,677 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:29:04,785 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/forms.py changed, reloading.
2025-09-18 19:29:05,626 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:29:09,838 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/forms.py changed, reloading.
2025-09-18 19:29:10,734 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:29:13,904 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/forms.py changed, reloading.
2025-09-18 19:29:14,761 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:36:08,078 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/forms.py changed, reloading.
2025-09-18 19:36:08,886 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:37:33,386 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/forms.py changed, reloading.
2025-09-18 19:37:34,218 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:39:16,979 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/forms.py changed, reloading.
2025-09-18 19:39:17,815 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:39:44,526 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/forms.py changed, reloading.
2025-09-18 19:39:45,339 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:40:41,911 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 19:40:42,717 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:41:02,227 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/forms.py changed, reloading.
2025-09-18 19:41:03,015 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:47:02,682 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/forms.py changed, reloading.
2025-09-18 19:47:03,475 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:50:01,362 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/forms.py changed, reloading.
2025-09-18 19:50:02,195 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:50:06,317 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/forms.py changed, reloading.
2025-09-18 19:50:07,155 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:50:23,606 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/forms.py changed, reloading.
2025-09-18 19:50:24,395 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:50:43,010 django.request WARNING  Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-09-18 19:50:53,052 django.request WARNING  Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-09-18 19:50:54,518 django.request WARNING  Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-09-18 19:52:23,803 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/crm/models/contact.py changed, reloading.
2025-09-18 19:52:24,659 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:53:47,924 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/crm/models/contact.py changed, reloading.
2025-09-18 19:53:48,715 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:54:11,259 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/models.py changed, reloading.
2025-09-18 19:54:12,058 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:54:17,172 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/models.py changed, reloading.
2025-09-18 19:54:17,998 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:54:43,670 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/models.py changed, reloading.
2025-09-18 19:54:44,480 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:54:53,685 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/models.py changed, reloading.
2025-09-18 19:54:54,266 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:54:59,462 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/models.py changed, reloading.
2025-09-18 19:55:00,064 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:55:09,329 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/models.py changed, reloading.
2025-09-18 19:55:10,113 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:55:14,202 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/models.py changed, reloading.
2025-09-18 19:55:15,013 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:55:24,253 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/models.py changed, reloading.
2025-09-18 19:55:25,054 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:55:30,204 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/models.py changed, reloading.
2025-09-18 19:55:31,036 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:55:33,070 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/models.py changed, reloading.
2025-09-18 19:55:33,886 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:55:35,456 django.request WARNING  Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-09-18 19:55:44,184 django.request WARNING  Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-09-18 19:55:49,742 django.request ERROR    Internal Server Error: /invoices/lead/create/5/
Traceback (most recent call last):
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/core/mixins.py", line 162, in form_valid
    instance = form.save(commit=False)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/billing/forms.py", line 188, in save
    instance = super().save(commit=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/billing/forms.py", line 172, in save
    obj.lead.pk = self._lead_pk
    ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'pk'
2025-09-18 19:56:10,456 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/forms.py changed, reloading.
2025-09-18 19:56:11,316 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:56:13,208 django.request WARNING  Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-09-18 19:56:29,522 django.request WARNING  Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-09-18 19:56:38,481 django.request WARNING  Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-09-18 19:56:50,489 django.request WARNING  Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-09-18 19:58:04,748 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/forms.py changed, reloading.
2025-09-18 19:58:05,640 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:58:14,006 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/forms.py changed, reloading.
2025-09-18 19:58:14,837 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:59:01,429 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/forms.py changed, reloading.
2025-09-18 19:59:02,267 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:59:28,138 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/forms.py changed, reloading.
2025-09-18 19:59:28,949 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:59:40,220 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/forms.py changed, reloading.
2025-09-18 19:59:40,985 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 19:59:43,018 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/forms.py changed, reloading.
2025-09-18 19:59:43,779 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:00:00,167 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/views.py changed, reloading.
2025-09-18 20:00:00,933 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:00:20,585 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 20:00:21,365 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:00:48,247 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 20:00:49,021 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:01:50,873 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 20:01:51,666 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:01:56,017 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 20:01:56,681 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:02:01,839 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 20:02:02,642 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:02:47,161 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 20:02:47,984 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:02:55,229 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 20:02:56,036 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:03:12,939 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 20:03:13,785 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:03:32,408 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 20:03:33,272 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:03:36,491 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 20:03:37,160 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:04:34,882 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 20:04:35,707 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:04:52,289 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 20:04:53,114 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:05:20,307 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/views.py changed, reloading.
2025-09-18 20:05:21,141 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:05:24,284 django.request ERROR    Internal Server Error: /invoices/lead/create/5/
Traceback (most recent call last):
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/edit.py", line 142, in get
    return self.render_to_response(self.get_context_data())
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/core/mixins.py", line 120, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/edit.py", line 72, in get_context_data
    kwargs["form"] = self.get_form()
                     ^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/edit.py", line 37, in get_form
    return form_class(**self.get_form_kwargs())
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/core/mixins.py", line 111, in get_form_kwargs
    if self.kwargs.get(paent_url):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'list'
2025-09-18 20:05:39,773 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 20:05:40,606 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:06:07,299 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 20:06:08,080 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:06:11,154 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 20:06:11,970 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:06:14,789 django.request ERROR    Internal Server Error: /invoices/lead/create/5/
Traceback (most recent call last):
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/edit.py", line 142, in get
    return self.render_to_response(self.get_context_data())
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/core/mixins.py", line 131, in get_context_data
    and self.kwargs.get(self.parent_url_kwarg) is not None
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'list'
2025-09-18 20:06:39,939 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/views.py changed, reloading.
2025-09-18 20:06:40,733 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:06:47,875 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 20:06:48,691 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:07:32,015 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 20:07:32,817 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:07:36,899 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 20:07:37,691 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:08:00,500 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 20:08:01,270 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:08:03,310 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 20:08:04,102 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:08:19,622 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 20:08:20,454 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:09:43,687 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 20:09:44,472 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:09:49,840 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 20:09:50,497 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:10:15,436 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 20:10:16,296 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:10:23,491 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/appointment/views.py changed, reloading.
2025-09-18 20:10:24,325 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:10:29,461 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/appointment/views.py changed, reloading.
2025-09-18 20:10:30,245 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:10:38,456 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/views.py changed, reloading.
2025-09-18 20:10:39,249 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:10:48,483 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/crm/views.py changed, reloading.
2025-09-18 20:10:49,351 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:11:02,690 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/leads/views.py changed, reloading.
2025-09-18 20:11:03,504 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:11:07,626 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/leads/views.py changed, reloading.
2025-09-18 20:11:08,414 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:11:17,717 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/views.py changed, reloading.
2025-09-18 20:11:18,512 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:11:20,586 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/views.py changed, reloading.
2025-09-18 20:11:21,407 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:11:27,588 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/views.py changed, reloading.
2025-09-18 20:11:28,453 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:11:40,791 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/crm/views.py changed, reloading.
2025-09-18 20:11:41,604 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:11:52,907 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 20:11:53,716 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:12:28,613 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/forms.py changed, reloading.
2025-09-18 20:12:29,407 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:12:37,859 django.request WARNING  Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-09-18 20:12:54,740 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/views.py changed, reloading.
2025-09-18 20:12:55,501 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:13:17,029 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 20:13:17,831 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:13:19,131 django.request WARNING  Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-09-18 20:13:55,923 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/models.py changed, reloading.
2025-09-18 20:13:56,747 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:14:00,820 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/models.py changed, reloading.
2025-09-18 20:14:01,614 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:14:04,455 django.request WARNING  Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-09-18 20:15:14,744 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 20:15:15,604 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:15:18,761 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 20:15:19,516 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:15:28,741 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 20:15:29,610 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:18:09,806 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 20:18:10,641 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:18:13,726 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-18 20:18:14,523 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-18 20:18:21,003 django.request WARNING  Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-09-18 20:18:27,584 django.request WARNING  Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-09-18 20:18:48,756 django.request WARNING  Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-09-18 20:18:52,483 django.request WARNING  Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-09-18 20:18:53,713 django.request WARNING  Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-09-18 20:18:58,707 django.request WARNING  Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-09-18 20:19:08,452 django.request WARNING  Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-09-19 09:30:00,968 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 09:30:57,890 django.request ERROR    Internal Server Error: /remunerations_staff/create/
Traceback (most recent call last):
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/edit.py", line 142, in get
    return self.render_to_response(self.get_context_data())
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/core/mixins.py", line 115, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/edit.py", line 72, in get_context_data
    kwargs["form"] = self.get_form()
                     ^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/edit.py", line 37, in get_form
    return form_class(**self.get_form_kwargs())
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/core/mixins.py", line 106, in get_form_kwargs
    for parent_url in self.parent_url_kwarg:
TypeError: 'NoneType' object is not iterable
2025-09-19 09:32:01,452 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-19 09:32:02,252 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 09:32:05,547 django.request ERROR    Internal Server Error: /remunerations_staff/create/
Traceback (most recent call last):
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/edit.py", line 142, in get
    return self.render_to_response(self.get_context_data())
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/core/mixins.py", line 150, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/edit.py", line 72, in get_context_data
    kwargs["form"] = self.get_form()
                     ^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/edit.py", line 37, in get_form
    return form_class(**self.get_form_kwargs())
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/core/mixins.py", line 106, in get_form_kwargs
    for parent_url in self.parent_url_kwarg:
TypeError: 'NoneType' object is not iterable
2025-09-19 09:32:25,082 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-19 09:32:25,865 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 09:32:36,812 django.request ERROR    Internal Server Error: /remunerations_staff/create/
Traceback (most recent call last):
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/edit.py", line 142, in get
    return self.render_to_response(self.get_context_data())
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/core/mixins.py", line 124, in get_context_data
    parent_kwargs = {
                    ^
TypeError: 'NoneType' object is not iterable
2025-09-19 09:32:59,067 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-19 09:32:59,839 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 10:25:41,594 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/tables.py changed, reloading.
2025-09-19 10:25:42,415 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 10:25:45,249 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/tables.py changed, reloading.
2025-09-19 10:25:46,020 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 10:25:51,180 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/tables.py changed, reloading.
2025-09-19 10:25:51,971 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 10:26:05,471 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/tables.py changed, reloading.
2025-09-19 10:26:06,289 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 10:26:52,803 django.request WARNING  Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-09-19 17:35:48,839 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 17:46:19,219 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/views.py changed, reloading.
2025-09-19 17:46:20,034 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 17:49:33,468 django.request WARNING  Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-09-19 17:49:35,205 django.request WARNING  Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-09-19 17:57:43,812 django.request WARNING  Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-09-19 17:59:25,108 django.request WARNING  Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-09-19 17:59:27,397 django.request ERROR    Internal Server Error: /paiements/invoices/
Traceback (most recent call last):
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/response.py", line 74, in resolve_template
    return get_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 567, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 17: 'endif', expected 'endblock'. Did you forget to register or load this tag?
2025-09-19 17:59:27,529 django.request WARNING  Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-09-19 17:59:27,825 django.request WARNING  Not Found: /favicon.ico
2025-09-19 17:59:35,870 django.request WARNING  Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-09-19 17:59:38,494 django.request WARNING  Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-09-19 17:59:40,161 django.request WARNING  Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-09-19 18:04:40,681 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/forms.py changed, reloading.
2025-09-19 18:04:41,519 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:04:43,554 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/forms.py changed, reloading.
2025-09-19 18:04:44,336 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:04:50,501 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/forms.py changed, reloading.
2025-09-19 18:04:51,271 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:05:07,686 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/views.py changed, reloading.
2025-09-19 18:05:08,495 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:05:19,782 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/views.py changed, reloading.
2025-09-19 18:05:20,579 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:05:32,902 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/forms.py changed, reloading.
2025-09-19 18:05:33,689 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:05:35,725 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/forms.py changed, reloading.
2025-09-19 18:05:36,499 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:07:14,109 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/views.py changed, reloading.
2025-09-19 18:07:14,924 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:07:21,062 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/views.py changed, reloading.
2025-09-19 18:07:21,845 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:08:09,724 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/forms.py changed, reloading.
2025-09-19 18:08:10,526 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:08:20,998 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/forms.py changed, reloading.
2025-09-19 18:08:21,857 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:10:21,966 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-19 18:10:22,763 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:10:27,897 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-19 18:10:28,710 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:10:33,835 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-19 18:10:34,621 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:10:48,978 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-19 18:10:49,821 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:10:52,912 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-19 18:10:53,715 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:16:34,604 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-19 18:16:35,385 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:17:06,249 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-19 18:17:07,067 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:17:22,535 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-19 18:17:23,318 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:18:58,095 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-19 18:18:58,874 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:19:01,942 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-19 18:19:02,722 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:20:39,277 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-19 18:20:40,029 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:20:54,441 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-19 18:20:55,227 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:21:39,527 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/views.py changed, reloading.
2025-09-19 18:21:40,340 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:21:43,407 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/views.py changed, reloading.
2025-09-19 18:21:44,207 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:22:00,638 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-19 18:22:01,420 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:22:36,496 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/models.py changed, reloading.
2025-09-19 18:22:37,299 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:22:40,397 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/views.py changed, reloading.
2025-09-19 18:22:41,233 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:23:02,865 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/forms.py changed, reloading.
2025-09-19 18:23:03,632 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:23:16,952 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/forms.py changed, reloading.
2025-09-19 18:23:17,750 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:23:21,844 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/forms.py changed, reloading.
2025-09-19 18:23:22,639 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:23:31,946 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/models.py changed, reloading.
2025-09-19 18:23:32,743 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:23:53,461 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/views.py changed, reloading.
2025-09-19 18:23:54,268 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:27:59,908 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/models.py changed, reloading.
2025-09-19 18:28:00,723 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:28:18,165 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/models.py changed, reloading.
2025-09-19 18:28:18,974 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:28:23,068 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/models.py changed, reloading.
2025-09-19 18:28:23,841 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:28:46,416 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/models.py changed, reloading.
2025-09-19 18:28:47,198 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:28:50,266 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/models.py changed, reloading.
2025-09-19 18:28:51,063 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:28:56,185 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/models.py changed, reloading.
2025-09-19 18:28:57,025 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:29:09,341 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/billing/models.py changed, reloading.
2025-09-19 18:29:10,119 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:29:21,377 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/forms.py changed, reloading.
2025-09-19 18:29:22,164 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:29:37,540 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/forms.py changed, reloading.
2025-09-19 18:29:38,318 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:29:40,365 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/forms.py changed, reloading.
2025-09-19 18:29:41,146 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:29:44,243 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/forms.py changed, reloading.
2025-09-19 18:29:45,032 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:30:26,543 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:31:58,186 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/urls.py changed, reloading.
2025-09-19 18:31:58,999 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:32:02,071 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/urls.py changed, reloading.
2025-09-19 18:32:02,850 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:32:11,050 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/urls.py changed, reloading.
2025-09-19 18:32:11,852 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:32:15,823 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/urls.py changed, reloading.
2025-09-19 18:32:16,565 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:32:29,782 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/views.py changed, reloading.
2025-09-19 18:32:30,533 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:33:23,029 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/views.py changed, reloading.
2025-09-19 18:33:23,800 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:33:25,805 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/views.py changed, reloading.
2025-09-19 18:33:26,622 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:33:55,333 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/urls.py changed, reloading.
2025-09-19 18:33:56,144 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:33:58,176 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/urls.py changed, reloading.
2025-09-19 18:33:58,960 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:34:01,011 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/urls.py changed, reloading.
2025-09-19 18:34:01,824 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:34:23,907 django.request ERROR    Internal Server Error: /paiements/invoices/
Traceback (most recent call last):
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django_filters/views.py", line 85, in get
    context = self.get_context_data(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/transactions/views.py", line 85, in get_context_data
    context["create_url"] = self.get_queryset().model.get_create_url()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/apps/transactions/models.py", line 179, in get_create_url
    return reverse(f"{cls._meta.app_label}:create_{cls._meta.model_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'create_clientpayment' not found. 'create_clientpayment' is not a valid view function or pattern name.
2025-09-19 18:34:48,246 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/transactions/urls.py changed, reloading.
2025-09-19 18:34:49,046 django.utils.autoreload INFO     Watching for file changes with StatReloader
2025-09-19 18:34:50,407 django.request ERROR    Internal Server Error: /paiements/invoices/
Traceback (most recent call last):
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taki/Desktop/octopus_crm/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'create_invoice_payment' not found. 'create_invoice_payment' is not a valid view function or pattern name.
2025-09-19 18:42:55,780 django.utils.autoreload INFO     /home/taki/Desktop/octopus_crm/apps/core/mixins.py changed, reloading.
2025-09-19 18:42:56,574 django.utils.autoreload INFO     Watching for file changes with StatReloader
